#!/usr/bin/env python3
"""Generates illustrative placeholder SVGs for Taki Hair into assets/images/.

These are abstract, hand-generated illustrations (soft gradients, hair-strand
curves, wood-grain and leaf motifs) meant to convey mood -- not photographs of
any real person, model, or salon. Re-run to regenerate; when real photography
arrives, replace files at the same path and update the <img src> in index.html.

Note: assets/images/hero-main.jpg is a real photo (not generated by this
script) -- see scripts/source/hero-main-original-mockup.png for provenance.
"""
import math
import os
import random

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "images")

IVORY = "#faf6ee"
BEIGE = "#f1e9da"
BEIGE_DARK = "#e6dac3"
BROWN_LIGHT = "#b9a684"
BROWN = "#8a7350"
BROWN_DEEP = "#5a4a34"
GREEN = "#6f7f5c"
GREEN_DEEP = "#4f5d43"
NEAR_BLACK_BROWN = "#2c2418"


def write(filename, content):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w") as f:
        f.write(content)
    print("wrote", path)


def svg(w, h, body, extra_defs=""):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}">\n<defs>\n{extra_defs}</defs>\n{body}\n</svg>\n'
    )


def lin_gradient(gid, c1, c2, x1=0, y1=0, x2=1, y2=1):
    return (
        f'<linearGradient id="{gid}" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">'
        f'<stop offset="0%" stop-color="{c1}"/>'
        f'<stop offset="100%" stop-color="{c2}"/>'
        f"</linearGradient>\n"
    )


def radial_gradient(gid, c1, c2, c1_opacity=0.9, c2_opacity=0):
    mid_opacity = c1_opacity * 0.45 + c2_opacity * 0.55
    return (
        f'<radialGradient id="{gid}" cx="50%" cy="45%" r="65%">'
        f'<stop offset="0%" stop-color="{c1}" stop-opacity="{c1_opacity}"/>'
        f'<stop offset="55%" stop-color="{c1}" stop-opacity="{mid_opacity:.3f}"/>'
        f'<stop offset="100%" stop-color="{c2}" stop-opacity="{c2_opacity}"/>'
        f"</radialGradient>\n"
    )


def blur_filter(fid, stddev):
    return f'<filter id="{fid}" x="-40%" y="-40%" width="180%" height="180%">' \
           f'<feGaussianBlur stdDeviation="{stddev}"/></filter>\n'


def hair_strands(w, h, n, colors, frizzy=False, op_range=(0.05, 0.16), seed=0,
                  y_pad=60, filter_id=None):
    """Soft, thick, blurred flowing bands suggesting locks of hair (not thin wire lines)."""
    random.seed(seed)
    paths = []
    filt = f' filter="url(#{filter_id})"' if filter_id else ""
    for i in range(n):
        x0 = w * (i + 0.5) / n + random.uniform(-w * 0.09, w * 0.09)
        spread = w * (0.3 if frizzy else 0.2)
        drift = random.uniform(-spread, spread)
        bend = random.uniform(-1, 1) * (0.6 if frizzy else 1)
        cx1 = x0 + drift * 0.25 + bend * w * 0.05
        cy1 = h * random.uniform(0.24, 0.34)
        cx2 = x0 + drift * 0.7 - bend * w * 0.03
        cy2 = h * random.uniform(0.64, 0.8)
        x1 = x0 + drift
        y1 = h + y_pad
        sw = random.uniform(w * 0.02, w * 0.05) if frizzy else random.uniform(w * 0.03, w * 0.065)
        op = random.uniform(*op_range)
        color = colors[i % len(colors)]
        paths.append(
            f'<path d="M{x0:.1f},{-y_pad} C{cx1:.1f},{cy1:.1f} {cx2:.1f},{cy2:.1f} '
            f'{x1:.1f},{y1:.1f}" stroke="{color}" stroke-width="{sw:.1f}" '
            f'fill="none" opacity="{op:.2f}" stroke-linecap="round"{filt}/>'
        )
    return "\n".join(paths)


def flyaways(w, h, n, color, seed=1):
    random.seed(seed)
    paths = []
    for _ in range(n):
        x0 = random.uniform(0, w)
        y0 = random.uniform(h * 0.05, h * 0.55)
        ang = random.uniform(0, math.pi * 2)
        length = random.uniform(14, 34)
        x1 = x0 + math.cos(ang) * length
        y1 = y0 + math.sin(ang) * length
        cx = (x0 + x1) / 2 + random.uniform(-10, 10)
        cy = (y0 + y1) / 2 + random.uniform(-10, 10)
        op = random.uniform(0.15, 0.3)
        paths.append(
            f'<path d="M{x0:.1f},{y0:.1f} Q{cx:.1f},{cy:.1f} {x1:.1f},{y1:.1f}" '
            f'stroke="{color}" stroke-width="1" fill="none" opacity="{op:.2f}" '
            f'stroke-linecap="round"/>'
        )
    return "\n".join(paths)


def wood_grain(w, y_top, y_bottom, n_lines, color, seed=2):
    random.seed(seed)
    lines = []
    step = (y_bottom - y_top) / max(n_lines, 1)
    for i in range(n_lines):
        y = y_top + step * i + random.uniform(-4, 4)
        amp = random.uniform(6, 16)
        op = random.uniform(0.08, 0.18)
        sw = random.uniform(1, 2.2)
        lines.append(
            f'<path d="M0,{y:.1f} Q{w*0.25:.1f},{y-amp:.1f} {w*0.5:.1f},{y:.1f} '
            f'T{w:.1f},{y:.1f}" stroke="{color}" stroke-width="{sw:.2f}" '
            f'fill="none" opacity="{op:.2f}"/>'
        )
    return "\n".join(lines)


def leaf(cx, cy, length, angle, color, opacity=0.5):
    w = length * 0.42
    return (
        f'<g transform="rotate({angle:.1f} {cx:.1f} {cy:.1f})">'
        f'<path d="M{cx:.1f},{cy:.1f} Q{cx+length*0.5:.1f},{cy-w:.1f} '
        f'{cx+length:.1f},{cy:.1f} Q{cx+length*0.5:.1f},{cy+w:.1f} {cx:.1f},{cy:.1f} Z" '
        f'fill="{color}" opacity="{opacity}"/>'
        f'<line x1="{cx:.1f}" y1="{cy:.1f}" x2="{cx+length*0.92:.1f}" y2="{cy:.1f}" '
        f'stroke="{BROWN_DEEP}" stroke-width="0.6" opacity="{opacity*0.5}"/>'
        f"</g>\n"
    )


def plant(cx, cy, scale, seed=3):
    random.seed(seed)
    tones = [GREEN, GREEN_DEEP, "#7f9169"]
    out = []
    for i, ang in enumerate([-55, -25, -5, 20, 45, 65]):
        length = scale * random.uniform(0.7, 1.15)
        out.append(leaf(cx, cy, length, ang - 90, random.choice(tones), 0.6))
    return "\n".join(out)


def gloss_highlight(w, h, gid="gloss", filter_id=None):
    filt = f' filter="url(#{filter_id})"' if filter_id else ""
    return (
        f'<ellipse cx="{w*0.32:.0f}" cy="{h*0.26:.0f}" rx="{w*0.4:.0f}" '
        f'ry="{h*0.11:.0f}" fill="url(#{gid})"{filt} '
        f'transform="rotate(-16 {w*0.32:.0f} {h*0.26:.0f})"/>'
    )


def vignette(w, h, gid="vig"):
    return f'<rect width="{w}" height="{h}" fill="url(#{gid})"/>'


def person_silhouette(w, h, skin, hair, garment, filter_id=None, hair_style="long"):
    """Soft out-of-focus portrait bokeh (no facial features) -- reads as a warm,
    inviting silhouette rather than a flat clipart avatar. hair_style="short"
    gives a cropped, close-to-the-head shape (male-presenting) with a simple
    open-collar hint instead of the flowing long-hair silhouette."""
    cx = w * 0.5
    head_cy = h * 0.36
    head_r = w * 0.2
    filt = f' filter="url(#{filter_id})"' if filter_id else ""

    if hair_style == "short":
        hair_rx, hair_ry = head_r * 0.98, head_r * 0.88
        hair_cy = head_cy - head_r * 0.12
        collar = (
            f'<path d="M{cx-head_r*0.55:.0f},{h*0.6:.0f} L{cx:.0f},{h*0.71:.0f} '
            f'L{cx+head_r*0.55:.0f},{h*0.6:.0f}" stroke="{skin}" '
            f'stroke-width="{w*0.018:.1f}" fill="none" opacity="0.45"/>'
        )
    else:
        hair_rx, hair_ry = head_r * 1.15, head_r * 1.3
        hair_cy = head_cy + head_r * 0.35
        collar = ""

    return f"""
  <g{filt}>
    <ellipse cx="{cx:.0f}" cy="{h*0.86:.0f}" rx="{w*0.42:.0f}" ry="{h*0.32:.0f}" fill="{garment}" opacity="0.9"/>
    {collar}
    <ellipse cx="{cx:.0f}" cy="{hair_cy:.0f}" rx="{hair_rx:.0f}" ry="{hair_ry:.0f}" fill="{hair}" opacity="0.85"/>
    <ellipse cx="{cx:.0f}" cy="{head_cy:.0f}" rx="{head_r*0.86:.0f}" ry="{head_r*0.92:.0f}" fill="{skin}" opacity="0.92"/>
  </g>
  <ellipse cx="{cx-head_r*0.5:.0f}" cy="{head_cy-head_r*0.5:.0f}" rx="{head_r*0.5:.0f}" ry="{head_r*0.4:.0f}"
           fill="#ffffff" opacity="0.12"{filt}/>
"""


def hair_mass_path(cx, top_y, bottom_y, top_w, mid_w, bottom_w, jitter, seed, n=16, mid_t=0.55):
    """Closed silhouette of hair seen from behind: wide near the crown, tapering
    or flaring toward the ends. `jitter` > 0 gives an uneven, frizzy edge."""
    random.seed(seed)
    left, right = [], []
    for i in range(n + 1):
        t = i / n
        y = top_y + (bottom_y - top_y) * t
        if t < mid_t:
            wgt = top_w + (mid_w - top_w) * (t / mid_t)
        else:
            wgt = mid_w + (bottom_w - mid_w) * ((t - mid_t) / (1 - mid_t))
        jl = random.uniform(-jitter, jitter)
        jr = random.uniform(-jitter, jitter)
        left.append((cx - wgt / 2 + jl, y))
        right.append((cx + wgt / 2 + jr, y))
    d = f"M{left[0][0]:.1f},{left[0][1]:.1f} "
    for p in left[1:]:
        d += f"L{p[0]:.1f},{p[1]:.1f} "
    for p in reversed(right):
        d += f"L{p[0]:.1f},{p[1]:.1f} "
    d += "Z"
    return d


def make_case(n, hair_tone, seed):
    """Back-view portrait: shoulders + hair mass filling most of the frame,
    seen from behind (no face), so the hair's texture/shape is the subject."""
    w, h = 640, 800
    cx = w * 0.5

    def render(is_after, filename):
        clip_id = f"hairclip{n}{'a' if is_after else 'b'}"
        bg_id = f"bg{n}{'a' if is_after else 'b'}"
        glow_id = f"glow{n}{'a' if is_after else 'b'}"
        soft_id = f"soft{n}{'a' if is_after else 'b'}"
        c1, c2 = hair_tone
        if is_after:
            hair_path = hair_mass_path(cx, 6, h * 0.9, w * 0.5, w * 0.46, w * 0.3,
                                        jitter=3, seed=seed, n=18, mid_t=0.35)
            strands = hair_strands(w, h, 8, [BEIGE_DARK, "#f4e8cc"], frizzy=False,
                                    op_range=(0.22, 0.36), seed=seed + 40, y_pad=20,
                                    filter_id=soft_id)
            gloss = gloss_highlight(w, h * 1.1, f"gloss{n}", filter_id=soft_id)
            hair_defs = (
                lin_gradient(bg_id, c2, c1, 0, 0, 1, 1)
                + radial_gradient(f"gloss{n}", "#fffaf0", "#fffaf0", 0.55, 0)
                + blur_filter(soft_id, 16)
            )
            extra = f'<g clip-path="url(#{clip_id})">{gloss}</g>'
        else:
            hair_path = hair_mass_path(cx, 4, h * 0.86, w * 0.56, w * 0.66, w * 0.58,
                                        jitter=16, seed=seed, n=20, mid_t=0.45)
            strands = hair_strands(w, h, 7, [BROWN, BROWN_DEEP], frizzy=True,
                                    op_range=(0.16, 0.26), seed=seed + 20, y_pad=20,
                                    filter_id=None)
            hair_defs = lin_gradient(bg_id, c1, c2, 0, 0, 1, 1)
            extra = f'<g>{flyaways(w, h, 30, BROWN_DEEP, seed=seed + 30)}</g>'

        defs = (
            hair_defs
            + radial_gradient(glow_id, "#fff8ec", "#fff8ec", 0.35, 0)
            + f'<clipPath id="{clip_id}"><path d="{hair_path}"/></clipPath>'
        )

        garment = BEIGE if is_after else BEIGE_DARK
        body = f"""
  <rect width="{w}" height="{h}" fill="{IVORY}"/>
  <circle cx="{w*0.5:.0f}" cy="{h*0.12:.0f}" r="{h*0.5:.0f}" fill="url(#{glow_id})"/>
  <g opacity="0.7">{wood_grain(w, h*0.82, h, 5, BROWN, seed=seed+8)}</g>
  <g>{plant(w*0.9, h*0.86, 90, seed=seed+13)}</g>
  <ellipse cx="{cx:.0f}" cy="{h*0.97:.0f}" rx="{w*0.4:.0f}" ry="{h*0.22:.0f}" fill="{garment}"/>
  <path d="{hair_path}" fill="url(#{bg_id})"/>
  <g clip-path="url(#{clip_id})">{strands}</g>
  {extra}
"""
        write(filename, svg(w, h, body, defs))

    render(False, f"case{n:02d}-before-placeholder.svg")
    render(True, f"case{n:02d}-after-placeholder.svg")


def make_salon(name, seed, glow_pos, leaf_pos, grain_band, base):
    w, h = 1200, 900
    defs = (
        lin_gradient("bgs", base[0], base[1], 0, 0, 1, 1)
        + radial_gradient("glows", "#fffaf0", "#fffaf0", 0.75, 0)
        + radial_gradient("glows2", "#fffaf0", "#fffaf0", 0.4, 0)
        + blur_filter("softSalon", 3)
        + blur_filter("softSalonSoft", 14)
    )
    gx, gy, gr = glow_pos
    lx, ly, ls = leaf_pos
    gtop, gbot = grain_band
    random.seed(seed + 20)
    table_x = w * random.uniform(0.42, 0.58)
    table_y = gtop + (h - gtop) * 0.28
    table_w = w * random.uniform(0.16, 0.24)
    body = f"""
  <rect width="{w}" height="{h}" fill="url(#bgs)"/>
  <circle cx="{gx}" cy="{gy}" r="{gr}" fill="url(#glows)"/>
  <circle cx="{w*0.5:.0f}" cy="{h*0.08:.0f}" r="{h*0.22:.0f}" fill="url(#glows2)"/>
  <g opacity="0.9">{wood_grain(w, gtop, gbot, 11, BROWN, seed=seed)}</g>
  <rect x="{table_x:.0f}" y="{table_y:.0f}" width="{table_w:.0f}" height="{h*0.05:.0f}" rx="6"
        fill="{BROWN_DEEP}" opacity="0.16" filter="url(#softSalonSoft)"/>
  <rect x="{table_x + table_w*0.15:.0f}" y="{table_y - h*0.16:.0f}" width="{table_w*0.7:.0f}"
        height="{h*0.16:.0f}" rx="8" fill="{IVORY}" opacity="0.3" filter="url(#softSalonSoft)"/>
  <g filter="url(#softSalon)">{plant(lx, ly, ls, seed=seed+5)}</g>
  <g filter="url(#softSalon)" opacity="0.8">{plant(w-lx, h*0.2, ls*0.6, seed=seed+9)}</g>
"""
    write(f"{name}-placeholder.svg", svg(w, h, body, defs))


def make_counseling():
    w, h = 1200, 900
    defs = (
        lin_gradient("bgc", BEIGE, BROWN_LIGHT, 0, 0, 1, 1)
        + radial_gradient("glowc", "#fff6e6", "#fff6e6", 0.55, 0)
        + blur_filter("softC", 18)
    )
    body = f"""
  <rect width="{w}" height="{h}" fill="url(#bgc)"/>
  <circle cx="{w*0.5}" cy="{h*0.32}" r="{h*0.5}" fill="url(#glowc)"/>
  <g opacity="0.85">{wood_grain(w, h*0.78, h, 6, BROWN, seed=7)}</g>
  <ellipse cx="{w*0.5}" cy="{h*0.46}" rx="{w*0.22}" ry="{h*0.3}" fill="{IVORY}" opacity="0.4" filter="url(#softC)"/>
  <rect x="{w*0.44}" y="{h*0.68}" width="{w*0.12}" height="{h*0.22}" rx="10" fill="{BROWN_DEEP}" opacity="0.16" filter="url(#softC)"/>
  <g>{plant(w*0.86, h*0.78, 110, seed=9)}</g>
  <g>{plant(w*0.1, h*0.82, 90, seed=13)}</g>
"""
    write("counseling-placeholder.svg", svg(w, h, body, defs))


def make_staff():
    w, h = 700, 900
    defs = (
        lin_gradient("bgst", BEIGE, BROWN_LIGHT, 0, 0, 1, 1)
        + radial_gradient("glowst", "#fff6e6", "#fff6e6", 0.6, 0)
        + blur_filter("softStaff", 9)
    )
    body = f"""
  <rect width="{w}" height="{h}" fill="url(#bgst)"/>
  <circle cx="{w*0.5}" cy="{h*0.4}" r="{h*0.45}" fill="url(#glowst)"/>
  {person_silhouette(w, h, "#c99b74", "#4a3a2c", "#a9a08e", filter_id="softStaff", hair_style="short")}
  <text x="{w-20}" y="{h-20}" text-anchor="end" font-family="'Noto Sans JP',sans-serif"
        font-size="13" fill="{BROWN_DEEP}" opacity="0.3">staff.jpg に差し替え推奨</text>
"""
    write("staff-placeholder.svg", svg(w, h, body, defs))


def make_og():
    w, h = 1200, 630
    defs = lin_gradient("bgog", GREEN_DEEP, BROWN_DEEP, 0, 0, 1, 1) + blur_filter("softOg", 24)
    body = f"""
  <rect width="{w}" height="{h}" fill="url(#bgog)"/>
  <g>{hair_strands(w, h, 8, [BEIGE_DARK], frizzy=False, op_range=(0.1, 0.2), seed=99, filter_id="softOg")}</g>
  <text x="60" y="330" font-family="'Shippori Mincho',serif" font-size="86" font-weight="700"
        fill="#ffffff">Taki Hair</text>
  <text x="64" y="380" font-family="'Noto Sans JP',sans-serif" font-size="28"
        fill="#f1e9da" opacity="0.9">高崎市の髪質改善サロン</text>
"""
    write("og-image-placeholder.svg", svg(w, h, body, defs))


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    make_case(1, (BROWN_LIGHT, BROWN), seed=101)
    make_case(2, (BEIGE_DARK, BROWN_LIGHT), seed=202)
    make_case(3, (BROWN, BROWN_DEEP), seed=303)
    make_counseling()
    make_staff()
    make_og()


if __name__ == "__main__":
    main()
